python36_test:
  image: python:3.6.8-alpine3.9
  script:
    - pip install pipenv
    - pipenv install --dev
    - pipenv install '-e .'
    - pipenv shell pytest --cov=febrl tests/


python37_test:
  image: python:3.7.4-alpine3.9
  script:
    - apk add git=2.20.1-r0 # Needed for coveralls
    - apk upgrade
    - pip install -e .
    - pytest --cov=febrl tests/
    - coveralls
